import { Router } from "express";
import { authCompany } from "../middlewares/auth.js";
import { listNotes, createNote, updateNote, deleteNote } from "../controllers/notes.controller.js";
const router = Router();
router.use(authCompany);
router.get("/", listNotes);
router.post("/", createNote);
router.put("/:id", updateNote);
router.delete("/:id", deleteNote);
export default router;
