import { Router } from 'express';
import * as ctrl from '../controllers/sales.controller.js';
const r=Router();
r.post('/sales/start', ctrl.startSale);
r.get('/sales', ctrl.listSales);
r.get('/sales/summary', ctrl.summarySales);
r.get('/sales/:id', ctrl.getSale);
r.patch('/sales/:id', ctrl.patchSale);
r.post('/sales/:id/items', ctrl.addItem);
r.patch('/sales/:id/items/:lineId', ctrl.updateItem);
r.delete('/sales/:id/items/:lineId', ctrl.removeItem);
r.post('/sales/:id/setCustomerVehicle', ctrl.setCustomerVehicle);
r.post('/sales/:id/addByQR', ctrl.addByQR);
r.post('/sales/:id/close', ctrl.closeSale);
r.post('/sales/:id/cancel', ctrl.cancelSale);
export default r;
